# -*- coding: utf-8 -*-
"""covid_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nxGCnWBsaLNxygBnIgc08Risnic3UYjz

# COVID-19 PROJECT

COVID-19 is an infectious disease caused by the Corona Virus, biologically known as severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2). The disease was first identified in Wuhan, the capital of China's Hubei province in December 2019 and has spread all over the world since then. As of writing this, on 26th April 2020, 21:57 IST, there are 2.92 million confirmed cases throughout the world and has resulted in 204,000 deaths according to Google.

In this notebook, I will take a look at the current situation in India. We will take a look at the regions which are most hampered by the outbreak and how numbers have steadily climbed in the country

To start off, we will import the necessary libraries which I will be using in my analysis and the different data tables from where I sourced my information.

# Step 1 : Preparing Environment and Importing libraries
"""

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from datetime import datetime

"""# Step 2:  Importing dataset"""

cd=pd.read_csv("covid_19_data.csv",parse_dates=['ObservationDate'],dayfirst=True)

"""# Step 3: Data wrangling/Processing

"""

#Explore and observe data
#Check for and treat missing or null values
#Transform data — format data type
#Perform preliminary statistical analysis

#DATA CLEANING AND MANIPULATION

cd.head(7)

cd.shape

cd.dtypes

cd.info()

cd=cd.rename(columns={'ObservationDate':'date','Province/State': 'state','Country/Region':'country','Recovered':'cured','Deaths':'deaths','Confirmed':'confirmed','Date':'date'})

cd

cd.drop(['SNo'],inplace=True,axis=1)

cd

cd.duplicated()

cd.columns

cd.isnull()

cd.isnull().sum()

cd=cd.dropna()

cd.isnull().sum()

cd.sample(n=10)

cd.corr()

cd["active"]=cd['confirmed']-(cd['cured']+cd['deaths'])

cd.tail(7)

country=cd.pivot_table(index='country',values=['confirmed','deaths','cured','active'],aggfunc=max)

country.tail()

country['m_rate']=country['deaths']*100/country['confirmed']

country['r_rate']=country['cured']*100/country['confirmed']

country.head()

country=country.sort_values(by='confirmed',ascending=False)
country.head()

"""# step: 4  ANALYZE THE DATA"""

cd.describe()

cd.nlargest(5, 'cured')

cd.nsmallest(5, 'deaths')

cd.nlargest(5, 'confirmed')

cd.nunique()

cd.count()

cd['state'].value_counts()

"""# Step : 5 Data Visualization"""

country.style.background_gradient(cmap='rainbow')

#Top active cases
top_10=country.head(10)
top_10_active=country.head(5)
top_10_active.reset_index().plot(kind='line',x='country',y='active',color='blue',linewidth=2,title='Top 5 country with most active cases',figsize=(20,10))
sns.set(font_scale=1.5)

top_10=country.head(10)
top_10.reset_index().plot(kind='bar',x='country',y='confirmed',title='Top 10 country with most number of confirmed cases',color=['Red'],figsize=(20,10))
#sns.set(font_scale=1.5)

top_10_deaths=top_10.sort_values(by='deaths',ascending=False)
top_10_deaths=top_10_deaths.head(5)

#Top states with highest deaths

top_10_deaths.reset_index().plot(kind='bar',x='country',y='deaths',title='Top 5 country with most number of deaths',color=['red','orange','blue','deepskyblue','green'],figsize=(15,10))
plt.ylabel("no.of deaths")
#sns.set(font_scale=3)

top_10=country.head(10)
top_10_cured=top_10.sort_values(by='cured',)
top_10_cured.reset_index().plot(kind='barh',x='country',y='cured',title='Top 10 country with most number of cured cases',color=['dodgerblue'],figsize=(20,10))
#sns.set(font_scale=1.5)

top_10=country.head(7)
top_10.reset_index().plot(kind='line',x='country',y='m_rate',title='Top 7 country with most number of m_rate',color='red',linestyle='-',linewidth=3,figsize=(15,8))
top_10.reset_index().plot(kind='scatter',x='country',y='r_rate',title='Top 7 country with most number of r_rate',color='green',marker='*',linewidth=4,figsize=(15,8))

top_ac=cd[cd.country=="India"]
top_ac

top_10=country.head(10)
sns.lineplot(y='deaths',x='date',color='green',data=top_ac).set(title="Date-wise analysis of death cases")
sns.set(rc={'figure.figsize':(18,8)})
#sns.set(font_scale=3)

fig=plt.figure(figsize=(20,10))
sns.heatmap(cd.corr(),annot=True)

sns.set(font_scale=2)
plt.show()

sns.pairplot(cd,hue="country")
plt.show()

country.hist(figsize=(20,15),bins=50,color='blue')
sns.set(font_scale=1)

state=cd.pivot_table(index='state',values=['confirmed','deaths','cured','active'],aggfunc=max)

state=state.sort_values(by='confirmed',ascending=False)

top_5=state.head()

top_5.reset_index().plot(kind='scatter',x='state',y='confirmed',color='blue',figsize=(20,10))
sns.set(font_scale=1)

"""# Step 6 : Act/Conclusion/Findings

#In the final step, we will be delivering our key insights 

1. What are the top country with highest number of deaths?
-> In UK number of deaths is comparatively higher (i.e above 1 lakhs)than the lower country that has least number of deaths like Brazil, India, US A=and Italy.

2. What are the top country with maximum number of active cases?
-> UK and US are amongst the most number of active cases affected by covid-19 and the data for this viz is above 37 lakhs as comapare to other countries.

3. What are the top country with maximum number of cured cases?
->Although US,INDIA,BRAZIL,PERU,RUSSIA,COLUMBIA,ITALY,GERMANY,SPAIN UK are the top country but amongst these countries US and INDIA are having the most cured cases.

4. What are the top country with most number of confirmed cases?
-> INDIA ,UK ,US ,BRAZIL and six other countries having the most confirmed cases but as compared to INDIA their cases are significantly lower but still high. 

5. What are the top country with most number of m_rate and r_rate?
-> BRAZIL and PERU has higher m_rate(mortality rate) but in case of r_rate data is different as PERU and US are having the higher r_rate(recovery rate)
"""